env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:   
  no-console: 0
  no-param-reassign: 0
  import/no-named-as-default: 0
